[DEFAULT]
upstream-branch = stable
debian-branch = feature/debian-package
# create the upstream tarball from the upstream branch
upstream-tree = branch
# Use a specific tag format (e.g., v1.0)
upstream-tag = v%(version)s
